putr/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index)
]

putr/putr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('requirements/', include('requirements.urls')),
    path('specifications/', include('specifications.urls')),
    path('releases/', include('releases.urls')),
    path('projects/', include('projects.urls')),
    path('auth/', include('authorization.urls')),
    path('admin/', admin.site.urls)
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

putr/requirements/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='requirements_home'),
    path('create/', views.create, name='requirements_create'),
    path('<int:pk>', views.RequirementsDetailView.as_view(), name='requirements_detail'),
    path('<int:pk>/update', views.RequirementsUpdateView.as_view(), name='requirements_update'),
    path('<int:pk>/delete', views.RequirementsDeleteView.as_view(), name='requirements_delete'),
]

putr/requirements/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class Requirements(models.Model):
    name = models.CharField('Имя', unique=True, max_length=50)
    description = models.TextField('Описание', max_length=250, blank=True, null=True)

    class RequirementStatuses(models.IntegerChoices):
        NEW = 1, 'Новое'
        REJECTED = 2, 'Отвергнуто'
        AGREED = 3, 'Согласовано'
        CANCELED = 4, 'Отменено'
        REALIZED = 5, 'Реализовано'
        UNREALIZED = 6, 'Нереализовано'

    status = models.SmallIntegerField('Статус', choices=RequirementStatuses.choices, default=RequirementStatuses.NEW)

    class RequirementTypes(models.IntegerChoices):
        FUNCTIONAL = 1, 'Функциональное'
        NONFUNCTIONAL = 2, 'Нефункциональное'
        __empty__ = 'Выберите тип требования'

    type = models.SmallIntegerField('Тип требования', choices=RequirementTypes.choices,
                                    default=RequirementTypes.__empty__)

    date_creation = models.DateTimeField('Дата создания')
    creator = models.CharField('Создатель', max_length=30)
    executor = models.CharField('Исполнитель', max_length=30)

    specification = models.ForeignKey('specifications.Specifications', verbose_name='Спецификация',
                                      on_delete=models.DO_NOTHING, blank=True, null=True,
                                      limit_choices_to={'status': 2})

    # linked_requirement = models.OneToOneField('self', verbose_name='Связанные требования', on_delete=models.DO_NOTHING, blank=True, null=True)
    linked_requirement = models.ManyToManyField('self', verbose_name='Связанные требования',
                                                # on_delete=models.DO_NOTHING,
                                                blank=True, null=True)

    class LinkTypes(models.IntegerChoices):
        HIERARCHY = 1, 'Иерархическая'
        DEPENDENCY = 2, 'Зависимость'

    link_type = models.SmallIntegerField('Тип связи', choices=LinkTypes.choices, blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/requirements/{self.id}'

    class Meta:
        verbose_name = 'Требование'
        verbose_name_plural = 'Требования'
        ordering = ['date_creation']
        get_latest_by = 'date_creation'

putr/requirements/forms.py
from .models import Requirements
from django.core.exceptions import ValidationError
from django.forms import ModelForm, TextInput, DateTimeInput, Textarea, Select, ModelMultipleChoiceField, SelectMultiple

full_block = ['name', 'description', 'type', 'specification', 'linked_requirement', 'link_type']


class RequirementsForm(ModelForm):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        action = kwargs.pop('action', None)
        self.custom_fields = {'user': user, 'action': action}
        super(RequirementsForm, self).__init__(*args, **kwargs)
        self.fields['linked_requirement'].queryset = Requirements.objects.exclude(
            id__exact=self.instance.id)
        self.call_block(user, action)

    def update_block_form(self, **kwargs):
        user = kwargs.pop('user', None)
        action = kwargs.pop('action', None)
        self.custom_fields = {'user': user, 'action': action}
        self.call_block(user, action)

    def get_custom_fields(self):
        return self.custom_fields

    def block_fields(self, block_fields):
        for field in block_fields:
            self.fields[field].widget.attrs['readonly'] = True

    def call_block(self, user, action):
        if user is not None and action == 'update':
            groups = list(map(lambda x: x.name, user.groups.all()))
            if 'Архитектор' in groups:
                self.block_fields(full_block)
            elif 'Руководитель проекта' in groups:
                block_head = full_block + ['executor']
                self.block_fields(block_head)

    class Meta:
        model = Requirements
        exclude = ['date_creation','creator']
        widgets = {
            'name': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Название требования',
            }),
            'description': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Описание'
            }),
            'status': Select(attrs={
                'class': 'form-control',
                'placeholder': 'Статус',
                'size': 1
            }),
            'type': Select(attrs={
                'class': 'form-control',
                'placeholder': 'Тип',
                'size': 1
            }),
            'date_creation': DateTimeInput(attrs={
                'class': 'form-control',
                'placeholder': 'Дата создания'
            }),
            'creator': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Создатель'
            }),
            'specification': Select(attrs={
                'class': 'form-control',
                'placeholder': 'Спецификация',
                'size': 1
            }),
            'executor': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Исполнитель'
            }),
            # 'linked_requirement': Select(attrs={
            #     'class': 'form-control',
            #     'placeholder': 'Связанное требование',
            #     'size': 3
            # }),
            'linked_requirement': SelectMultiple(attrs={
                'class': 'form-control',
                'placeholder': 'Тип связи',
            }),
            'link_type': Select(attrs={
                'class': 'form-control',
                'placeholder': 'Тип связи',
                'size': 1
            })
        }

putr/requirements/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.contrib import auth
from .models import Requirements
from django.views.generic import DetailView, UpdateView, DeleteView
from .forms import RequirementsForm


def index(request):
    if request.user.is_authenticated:
        requirements = Requirements.objects.all()
        return render(request, 'requirements/index.html', {'requirements': requirements})
    else:
        return render(request, 'authorization/login.html')


class RequirementsDetailView(DetailView):
    model = Requirements
    template_name = 'requirements/detail_view.html'
    context_object_name = 'requirement'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            self.object = self.get_object()
            context = self.get_context_data(object=self.object)
            return self.render_to_response(context)
        else:
            return render(request, 'authorization/login.html')


class RequirementsUpdateView(UpdateView):
    model = Requirements
    template_name = 'requirements/update.html'
    form_class = RequirementsForm

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            self.object = self.get_object()
            form_class = self.get_form_class()
            form = self.get_form(form_class)
            form.update_block_form(user=request.user, action='update')
            context = self.get_context_data(object=self.object)
            context['form'] = form
            return self.render_to_response(context)
        else:
            return render(request, 'authorization/login.html')


class RequirementsDeleteView(DeleteView):
    model = Requirements
    success_url = 'requirements/'
    template_name = 'requirements/delete.html'
    context_object_name = 'requirement'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            self.object = self.get_object()
            context = self.get_context_data(object=self.object)
            return self.render_to_response(context)
        else:
            return render(request, 'authorization/login.html')


def create(request):
    if request.user.is_authenticated:
        error = ''
        if request.method == 'POST':
            form = RequirementsForm(request.POST)
            if form.is_valid():
                post = form.save(commit=False)
                post.creator = request.user
                post.date_creation = timezone.now()
                post.status = 1
                post.save()
                return redirect('requirements_home')
            else:
                error = 'Форма была неверной'
        form = RequirementsForm()
        data = {
            'form': form,
            'error': error
        }
        return render(request, 'requirements/create.html', data)
    else:
        return render(request, 'authorization/login.html')

putr/requirements/templates/requirements/create.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}
    Создание требования
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'requirements/css/index.css' %}">
{% endblock %}

{% block body %}
    <h2 align="center">Создание требования</h2>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <span> {{ error }} </span>
        <div style="width: 100%; height: 20px"></div>
        <button class="btn btn-success" type="submit">Создать требование</button>
    </form>

{% endblock %}

putr/requirements/templates/requirements/delete.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}
    Удаление требования
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'projects/css/index.css' %}">
{% endblock %}

{% block body %}
    <h2 align="center">Удаление требования</h2>
    <form method="post">
        {% csrf_token %}
        <h1>{{ requirement.name }}</h1>
        <p>Описание: {{ requirement.description }}</p>
        <p>Дата создания: {{ requirement.date_creation }}</p>
        <p>Создал: {{ requirement.creator }}</p>
        <p>Статус: {{ requirement.get_status_display }}</p>
        <p>Тип: {{ requirement.get_type_display }}</p>
        <p>Исполнитель: {{ requirement.executor }}</p>
        <p>Спецификация:
            <a href="{% url 'specifications_detail' requirement.specification.id %}">
            {{ requirement.specification }}
            </a>
        </p>
        <p>Связанное требование: {{ requirement.linked_requirement }}</p>
        <p>Тип связи: {{ requirement.get_link_type_display }}</p>
        <button class="btn btn-danger" type="submit">Удалить требование?</button>
    </form>

{% endblock %}

putr/requirements/templates/requirements/detail_view.html
{% extends 'main/layout.html' %}
{% load static %}
{% load auth_extras %}

{% block title %}
    {{ requirement.name }}
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'requirements/css/index.css' %}">
{% endblock %}

{% block body %}

    <div class="features" align="center">
        <h1>{{ requirement.name }}</h1>
        <p>Описание: {{ requirement.description }}</p>
        <p>Дата создания: {{ requirement.date_creation }}</p>
        <p>Создал: {{ requirement.creator }} </p>
{#        {{ requirement.creator.first_name}} {{ requirement.creator.last_name }}#}
        <p>Статус: {{ requirement.get_status_display }}</p>
        <p>Тип: {{ requirement.get_type_display }}</p>
        <p>Исполнитель: {{ requirement.executor }}</p>
        <p>Спецификация:
            <a href="{% url 'specifications_detail' requirement.specification.id %}">
            {{ requirement.specification }}
            </a>
        </p>
        <p>Связанные требования:
            <ul>
                {% for req in requirement.linked_requirement.all %}
                    <a href="{% url 'requirements_detail' req.id %}">
                        <p>{{req.name }}</p>
                    </a>
                {% endfor %}
            </ul>
        </p>
        <p>Тип связи: {{ requirement.get_link_type_display }}</p>
        {% if user|has_group:"Администратор" or user|has_group:"Аналитик"%}
            <a href="{% url 'requirements_delete' requirement.id %}" class="btn btn-danger">Удалить</a>
        {% endif %}
        {% if user|has_group:"Администратор" or user|has_group:"Аналитик" or user|has_group:"Руководитель проекта" or user|has_group:"Архитектор"%}
            <a href="{% url 'requirements_update' requirement.id %}" class="btn btn-info">Редактировать</a>
        {% endif %}
    </div>
{% endblock %}

putr/requirements/templates/requirements/index.html
{% extends 'main/layout.html' %}
{% load static %}
{% load auth_extras %}

{% block title %}
    Требования
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'requirements/css/index.css' %}">
{% endblock %}

{% block body %}
    <div style="width: 100%; height: 20px"></div>
    <div class="container2">
        <div style="width: 25%; height: 100%"></div>
        <div style="width: 30%; height: 100%">
            <div class="container3">
                <div class="rel-header">Требования</div>
                <div style="width: 20%; height: 100%">
                    {% if user|has_group:"Администратор" or user|has_group:"Аналитик" %}
                        <a href="{% url 'requirements_create' %}"><button class="btn btn-primary"><i class="far fa-plus-square"></i></button></a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div style="width: 45%; height: 100%"></div>
    </div>
    <div class="container3">
        <div style="width: 25%; height: 100%"></div>
        <div style="width: 75%; height: 100%">
            {% for req in requirements %}
                <li>
                    <div class="container3">
                        <div style="width: 5%; height: 100%; margin-right: 10px">
                            <i class="far fa-file-alt"></i></i>
                        </div>
                        <div style="width: 95%; height: 100%; display: flex; flex-direction: row">
                            <a href="{% url 'requirements_detail' req.id %}">{{ req.name }}</a>
                            <div style="color: black; margin-left: 10px; margin-right: 10px">(Спецификация</div>
                            <a href="{% url 'specifications_detail' req.specification.id %}"> {{ req.specification.version }}</a>
                            <div style="color: black; margin-left: 0; margin-right: 10px">)</div>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </div>
    </div>

{% endblock %}

putr/requirements/templates/requirements/update.html
{% extends 'main/layout.html' %}
{% load static %}
{% load auth_extras %}

{% block title %}
    Редактирование требования
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'requirements/css/index.css' %}">
{% endblock %}

{% block body %}
    <h2 align="center">Редактирование требования</h2>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <span> {{ error }} </span>
        <div style="width: 100%; height: 20px"></div>
        <button class="btn btn-success" type="submit">Обновить требование</button>
    </form>
    {% if user|has_group:"Архитектор"%}
        <script>
            document.querySelectorAll('select:not([id="id_status"])').forEach(e=>e.style.pointerEvents = 'None');
        </script>
    {% endif %}

{% endblock %}